  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Install Expo CLI Globally
        run: npm install -g expo-cli

      - name: Check Expo CLI Version
        run: expo --version || echo "Expo CLI is not installed correctly"

      - name: Export Expo App for Web (With Debugging)
        run: |
          set -x  # Enable debugging mode (prints all commands)
          npx expo export:web || echo "❌ Expo export failed"

      - name: List Project Files (After Build)
        run: ls -R

      - name: Check if web-build folder exists
        run: |
          if [ -d "./web-build" ]; then
            echo "✅ web-build folder exists.";
          else
            echo "❌ web-build folder does NOT exist. Something went wrong with the build.";
            exit 1;
          fi

      - name: Zip artifact for deployment
        run: zip -r release.zip ./web-build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip
