name: Build and deploy Expo web app to Azure Web App - signbridge1

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Install new Expo CLI
        run: npm install -g @expo/cli
      

      - name: Verify Expo CLI installation
        run: npx expo --version
      
      - name: Build Expo Web App
        run: npx expo export --platform web
      
      - name: Check if dist folder exists
        run: |
          if [ -d "./dist" ]; then
            echo "✅ dist folder exists.";
          else
            echo "❌ dist folder does NOT exist. Something went wrong with the build.";
            exit 1;
          fi
      
      
      - name: Zip build artifact
        run: zip -r release.zip ./dist

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_37825F584B14483E877CA60B4DB962BF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F3332CBA578542249529AA6388E61ED1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BDEA5B0C55C04AED91EF697054857EC1 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'signbridge1'
          slot-name: 'Production'
          package: ./web-build
