name: Build and deploy Node.js app to Azure Web App - signbridge1

on:
  push:
    branches:
      - master
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Export Expo App for Web
        run: npx expo export:web

      - name: Zip Exported Files
        run: zip -r release.zip ./web-build

      - name: Upload Artifact for Deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download Exported Artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip Exported Files
        run: unzip release.zip -d web-build
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_37825F584B14483E877CA60B4DB962BF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F3332CBA578542249529AA6388E61ED1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BDEA5B0C55C04AED91EF697054857EC1 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'signbridge1'
          slot-name: 'Production'
          package: ./web-build
